/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface AutoGenerated {}
/**
 * This interface was referenced by `AutoGenerated`'s JSON-Schema
 * via the `definition` "responses/get_user".
 */
export interface GetUserResponse {
  user: UserDetail
}
export interface UserDetail {
  id: number
  name: string
  email: string
  date_of_birth: string
}
/**
 * This interface was referenced by `AutoGenerated`'s JSON-Schema
 * via the `definition` "responses/get_users".
 */
export interface GetUsersResponse {
  /**
   * An array of user summaries
   */
  users: UserSummary[]
  pagination: Pagination
}
export interface UserSummary {
  id: number
  name: string
}
/**
 * The pagination information for a collection
 */
export interface Pagination {
  /**
   * The total number of entries in the collection
   */
  total_entries: number
  /**
   * The requested page
   */
  current_page: number
  /**
   * The number of entries that we tried to load for this page
   */
  per_page: number
}
